### ISSUE TITLE
Shorten FHIR property names or use superproperties?

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#69]
Back when FHIR RDF R4 was first designed, the FHIR community allowed different FHIR resources to use the same property names for potentially different purposes: there was no official coordination of property names across resources.  As a consequence, when R4 was designed, we opted to fully qualify the property names to ensure that they would be semantically distinct.  For example, the "severity" property within an AllergyIntolerance reaction was given the fully qualified name `fhir:AllergyIntolerance.reaction.severity` instead of just `fhir:severity`.

Fast forward a few years, and the the FHIR community is now trying to be more rigorous about consistent naming of properties across FHIR resources, such that the same property name should have the same semantics across different resources.  This could allow us to shorten property names in RDF instead of using a path to construct a fully qualified name.  Should we shorten property names?   Or define superproperties with short names?  See [FHIR Five Ws page](https://build.fhir.org/fivews.html)

For example (but we need a better one), instead of writing this:  

```
fhir:AllergyIntolerance.reaction.severity [ fhir:value "moderate" ];
```
perhaps we could now write this:

```
fhir:severity [ fhir:value "moderate" ];
```

Would this be a good idea?  Would it work out well or cause problems?

**Comment by ericprud** [comment]
When @jmandel  and I started on this venture, Josh pointed out that there was no management to align the property names in different Resources (e.g. an Observation.foo may not equal Procedure.foo). StructureDefinitions already included fully-qualified names so it made sense to use those for FHIR/RDF. Since then, the fivews effort has aligned some (most? all?) of the properties in the core Resources. (Need link to the very wide fivews table that maps Resource-specific properties to fivews concepts.)

This effort has lead to re-used semantic names for properties (e.g. [Observation.subject](http://build.fhir.org/observation#Observation.subject) and [Condition.subject](http://build.fhir.org/condition.html#Condition.subject)) and good reasons when they differ. For instance, [Observation.subject](http://build.fhir.org/observation#Observation.subject) and [Immunization.patient](http://build.fhir.org/immunization.html#Immunization.patient) differ because the specificity of the recipient of an Immunization is higher (`Reference(Patient)`) than that of an Observation (`Patient | Group | Device | Location | Organization | Procedure | Practitioner | Medication | Substance`). The fivews heading for both of these is `@@TBD1` [resolve with spreadsheet].

On a conceptual level, this is all easily captured in RDFS:
``` turtle
fhir:Observation.subject rdfs:subPropertyOf fhir:subject .
fhir:Condition.subject rdfs:subPropertyOf fhir:subject .
fhir:Immunization.patient rdfs:subPropertyOf fhir:patient .
```
If we take the fivews headings as hallowed, we could add:
``` turtle
fhir:subject rdfs:subPropertyOf fhir:@@TBD1 .
fhir:patient rdfs:subPropertyOf fhir:@@TBD1 .
```
Note, I'm not advocating for real-time involvement of RDFS; just using it to formalize the apparent subsumption.

So now we have three possible names for Observation.subject and I would argue we want to choose exactly one to make interop practical. DL modeling principles suggest reusing general properties (c.f. using a "topping" property for both pizzas and ice cream), so we could use the fivews column name if possible. It would not be possible if fivews column names are not unique.

In addition to semantic clarity, we have to consider pallatability. FHIR developers are used to seeing the names of properties in those nice HTML tables and using those property names in instance data. Right now, that's a bit painful for RDF-heads because they have to add the full qualification. We could improve dev's lives by restricting to just the property name (in the `fhir:` namespace).

Using property  will never be ambiguous because if it were, it would be ambiguous in every FHIR representation and addressed immediately. Note that the same property name may appear in multiple places in a Resource, e.g. the `fhir:code`s in:
### Schema with multiple codes
``` shex
<#Observation> CLOSED {
  a [fhir:Observation] ;
  fhir:code @<#CodeableConcept> ;
  fhir:component CLOSED {
    fhir:code  @<#CodeableConcept> ;
    fhir:value  @<#CodeableConcept> OR @<#Quantity> ;
  } *
}
```
### Data with multiple codes
``` turtle
<Observation/BP123> a fhir:Observation ;
  fhir:code [ a fhir:CodeableConcept ;
    fhir:coding [ a fhir:Coding ;
                  fhir:system [ fhir:value "http://loinc.org" ] ;
                  fhir:code [ fhir:value "35094-2" ] ] ] ;
  fhir:component [
      fhir:code [ a fhir:CodeableConcept ;
        fhir:coding [ a fhir:Coding ;
                      fhir:system [ fhir:value "http://loinc.org" ] ;
                      fhir:code [ fhir:value "8480-6" ] ] ] ;
      fhir:value [ a fhir:Quantity ; fhir:value 120.0 ]
    ], [
      fhir:code [ a fhir:CodeableConcept ;
        fhir:coding [ a fhir:Coding ;
                      fhir:system [ fhir:value "http://loinc.org" ] ;
                      fhir:code [ fhir:value "8453-3" ] ] ] ;
      fhir:value [ a fhir:Quantity ; fhir:value 80.0 ]
    ]
.
```
[[try it](http://shex.io/webapps/shex.js/doc/shex-simple.html?schema=PREFIX%20fhir%3A%20%3Chttp%3A%2F%2Fhl7.org%2Ffhir%23%3E%0ABASE%20%3Chttp%3A%2F%2Fhl7.org%2Ffhir%2Fschema%3E%0A%0A%3C%23Observation%3E%20CLOSED%20%7B%0A%20%20a%20%5Bfhir%3AObservation%5D%20%3B%0A%20%20fhir%3Acode%20%40%3C%23CodeableConcept%3E%20%3B%0A%20%20fhir%3Acomponent%20CLOSED%20%7B%0A%20%20%20%20fhir%3Acode%20%20%40%3C%23CodeableConcept%3E%20%3B%0A%20%20%20%20fhir%3Avalue%20%20%40%3C%23CodeableConcept%3E%20OR%20%40%3C%23Quantity%3E%20%3B%0A%20%20%7D%20*%0A%7D%0A%0A%3C%23CodeableConcept%3E%20CLOSED%20%7B%0A%20%20a%20%5Bfhir%3ACodeableConcept%5D%20%3B%0A%20%20fhir%3Acoding%20%40%3C%23Coding%3E%20*%0A%7D%0A%0A%3C%23Coding%3E%20CLOSED%20%7B%0A%20%20a%20%5Bfhir%3ACoding%5D%20%3B%0A%20%20fhir%3Asystem%20%40%3C%23string%3E%20%3B%0A%20%20fhir%3Acode%20%40%3C%23string%3E%20%3B%0A%7D%0A%0A%3C%23string%3E%20CLOSED%20%7B%0A%20%20fhir%3Avalue%20LITERAL%0A%7D%0A%0A%3C%23Quantity%3E%20CLOSED%20%7B%0A%20%20a%20%5Bfhir%3AQuantity%5D%20%3B%0A%20%20fhir%3Avalue%20LITERAL%0A%7D&data=PREFIX%20fhir%3A%20%3Chttp%3A%2F%2Fhl7.org%2Ffhir%23%3E%0ABASE%20%3Chttp%3A%2F%2Fa.example%2Ffhir%2F%3E%0A%0A%3CObservation%2FBP123%3E%20a%20fhir%3AObservation%20%3B%0A%20%20fhir%3Acode%20%5B%20a%20fhir%3ACodeableConcept%20%3B%0A%20%20%20%20fhir%3Acoding%20%5B%20a%20fhir%3ACoding%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3Asystem%20%5B%20fhir%3Avalue%20%22http://loinc.org%22%20%5D%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3Acode%20%5B%20fhir%3Avalue%20%2235094-2%22%20%5D%20%5D%20%5D%20%3B%0A%20%20fhir%3Acomponent%20%5B%0A%20%20%20%20%20%20fhir%3Acode%20%5B%20a%20fhir%3ACodeableConcept%20%3B%0A%20%20%20%20%20%20%20%20fhir%3Acoding%20%5B%20a%20fhir%3ACoding%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3Asystem%20%5B%20fhir%3Avalue%20%22http://loinc.org%22%20%5D%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3Acode%20%5B%20fhir%3Avalue%20%228480-6%22%20%5D%20%5D%20%5D%20%3B%0A%20%20%20%20%20%20fhir%3Avalue%20%5B%20a%20fhir%3AQuantity%20%3B%20fhir%3Avalue%20120.0%20%5D%0A%20%20%20%20%5D%2C%20%5B%0A%20%20%20%20%20%20fhir%3Acode%20%5B%20a%20fhir%3ACodeableConcept%20%3B%0A%20%20%20%20%20%20%20%20fhir%3Acoding%20%5B%20a%20fhir%3ACoding%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3Asystem%20%5B%20fhir%3Avalue%20%22http://loinc.org%22%20%5D%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3Acode%20%5B%20fhir%3Avalue%20%228453-3%22%20%5D%20%5D%20%5D%20%3B%0A%20%20%20%20%20%20fhir%3Avalue%20%5B%20a%20fhir%3AQuantity%20%3B%20fhir%3Avalue%2080.0%20%5D%0A%20%20%20%20%5D%0A.&manifestURL=http%3A%2F%2Fshex.io%2Fwebapps%2Fshex.js%2Fexamples%2Fmanifest.json&shape-map=%3CObservation%2FBP123%3E%40%3C%23Observation%3E&interface=human&success=proof&regexpEngine=eval-threaded-nerr)]

This unifies three kinds of code into one term:
1. Observation.code
2. Observation.component.code
3. Coding.code

1 and 2 are pretty obviously the same thing so I believe it's non-controversial to merge them. 3 is a different beast in structure (it's a string (well, a bnode with a fhir:value if we're being persnickety)) instead of a CodeableConcept. Ordinarily, I don't think that datatypes should differentiate RDF properties (valueQuantity vs. valueCodeableConcept) but 3 feels so different as to maybe be worth differentiating. One principled way to attack this would be to only shortent Resource properties, not datatype properties:

### Schema with fully-qualified datatypes
``` shex
<#CodeableConcept> CLOSED {
  a [fhir:CodeableConcept] ;
  fhir:CodeableConcept.coding @<#Coding> *
}

<#Coding> CLOSED {
  a [fhir:Coding] ;
  fhir:Coding.system @<#string> ;
  fhir:Coding.code @<#string> ;
}
```
### Data with fully-qualified datatypes
``` turtle
<Observation/BP123> a fhir:Observation ;
  fhir:code [ a fhir:CodeableConcept ;
    fhir:CodeableConcept.coding [ a fhir:Coding ;
                  fhir:Coding.system [ fhir:value "http://loinc.org" ] ;
                  fhir:Coding.code [ fhir:value "35094-2" ] ] ] ;
  fhir:component [
      fhir:code [ a fhir:CodeableConcept ;
        fhir:CodeableConcept.coding [ a fhir:Coding ;
                      fhir:Coding.system [ fhir:value "http://loinc.org" ] ;
                      fhir:Coding.code [ fhir:value "8480-6" ] ] ] ;
      fhir:value [ a fhir:Quantity ; fhir:value 120.0 ]
    ], [
      fhir:code [ a fhir:CodeableConcept ;
        fhir:CodeableConcept.coding [ a fhir:Coding ;
                      fhir:Coding.system [ fhir:value "http://loinc.org" ] ;
                      fhir:Coding.code [ fhir:value "8453-3" ] ] ] ;
      fhir:value [ a fhir:Quantity ; fhir:value 80.0 ]
    ]
.
```
[[try it](http://shex.io/webapps/shex.js/doc/shex-simple.html?schema=PREFIX%20fhir%3A%20%3Chttp%3A%2F%2Fhl7.org%2Ffhir%23%3E%0ABASE%20%3Chttp%3A%2F%2Fhl7.org%2Ffhir%2Fschema%3E%0A%0A%3C%23Observation%3E%20CLOSED%20%7B%0A%20%20a%20%5Bfhir%3AObservation%5D%20%3B%0A%20%20fhir%3Acode%20%40%3C%23CodeableConcept%3E%20%3B%0A%20%20fhir%3Acomponent%20CLOSED%20%7B%0A%20%20%20%20fhir%3Acode%20%20%40%3C%23CodeableConcept%3E%20%3B%0A%20%20%20%20fhir%3Avalue%20%20%40%3C%23CodeableConcept%3E%20OR%20%40%3C%23Quantity%3E%20%3B%0A%20%20%7D%20*%0A%7D%0A%0A%3C%23CodeableConcept%3E%20CLOSED%20%7B%0A%20%20a%20%5Bfhir%3ACodeableConcept%5D%20%3B%0A%20%20fhir%3ACodeableConcept.coding%20%40%3C%23Coding%3E%20*%0A%7D%0A%0A%3C%23Coding%3E%20CLOSED%20%7B%0A%20%20a%20%5Bfhir%3ACoding%5D%20%3B%0A%20%20fhir%3ACoding.system%20%40%3C%23string%3E%20%3B%0A%20%20fhir%3ACoding.code%20%40%3C%23string%3E%20%3B%0A%7D%0A%0A%3C%23string%3E%20CLOSED%20%7B%0A%20%20fhir%3Avalue%20LITERAL%0A%7D%0A%0A%3C%23Quantity%3E%20CLOSED%20%7B%0A%20%20a%20%5Bfhir%3AQuantity%5D%20%3B%0A%20%20fhir%3Avalue%20LITERAL%0A%7D&data=PREFIX%20fhir%3A%20%3Chttp%3A%2F%2Fhl7.org%2Ffhir%23%3E%0ABASE%20%3Chttp%3A%2F%2Fa.example%2Ffhir%2F%3E%0A%0A%3CObservation%2FBP123%3E%20a%20fhir%3AObservation%20%3B%0A%20%20fhir%3Acode%20%5B%20a%20fhir%3ACodeableConcept%20%3B%0A%20%20%20%20fhir%3ACodeableConcept.coding%20%5B%20a%20fhir%3ACoding%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3ACoding.system%20%5B%20fhir%3Avalue%20%22http://loinc.org%22%20%5D%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3ACoding.code%20%5B%20fhir%3Avalue%20%2235094-2%22%20%5D%20%5D%20%5D%20%3B%0A%20%20fhir%3Acomponent%20%5B%0A%20%20%20%20%20%20fhir%3Acode%20%5B%20a%20fhir%3ACodeableConcept%20%3B%0A%20%20%20%20%20%20%20%20fhir%3ACodeableConcept.coding%20%5B%20a%20fhir%3ACoding%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3ACoding.system%20%5B%20fhir%3Avalue%20%22http://loinc.org%22%20%5D%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3ACoding.code%20%5B%20fhir%3Avalue%20%228480-6%22%20%5D%20%5D%20%5D%20%3B%0A%20%20%20%20%20%20fhir%3Avalue%20%5B%20a%20fhir%3AQuantity%20%3B%20fhir%3Avalue%20120.0%20%5D%0A%20%20%20%20%5D%2C%20%5B%0A%20%20%20%20%20%20fhir%3Acode%20%5B%20a%20fhir%3ACodeableConcept%20%3B%0A%20%20%20%20%20%20%20%20fhir%3ACodeableConcept.coding%20%5B%20a%20fhir%3ACoding%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3ACoding.system%20%5B%20fhir%3Avalue%20%22http://loinc.org%22%20%5D%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20fhir%3ACoding.code%20%5B%20fhir%3Avalue%20%228453-3%22%20%5D%20%5D%20%5D%20%3B%0A%20%20%20%20%20%20fhir%3Avalue%20%5B%20a%20fhir%3AQuantity%20%3B%20fhir%3Avalue%2080.0%20%5D%0A%20%20%20%20%5D%0A.&manifestURL=http%3A%2F%2Fshex.io%2Fwebapps%2Fshex.js%2Fexamples%2Fmanifest.json&shape-map=%3CObservation%2FBP123%3E%40%3C%23Observation%3E&interface=human&success=proof&regexpEngine=eval-threaded-nerr)]

**Comment by dbooth-boston** [comment]
Excellent summary! This will be very helpful for getting input from other FHIR/RDF users, to decide what we want in R5.

**Comment by hsolbrig** [comment]
Related documents: 

https://github.com/HL7/fhir/blob/master/source/w5.ini
https://github.com/HL7/fhir/blob/master/source/status-codes.xml
https://github.com/HL7/fhir/blob/master/source/compartments.xml

Don't know which, if any, apply

**Comment by dbooth-boston** [comment]
I think the main question is whether we could shorten property names without causing the property to become both an object property and a datatype property, as described in issue #102 .

**Comment by dbooth-boston** [comment]
AGREED: Shorten property names

https://www.w3.org/2022/07/28-hcls-minutes.html#t03

**Comment by dbooth-boston** [comment]
Re-opening to discuss: Punning: property fhir:Medication.code shortened to fhir:code, but fhir:code is already a class

**Comment by dbooth-boston** [comment]
Option 1: Use OWL punning.  Have both a class fhir:code and a property fhir:code

Option 2: Revert to fully qualified property names, such as fhir:Medication.code

Option 3: Change the class to start with an upper case: fhir:Code

Option 4: Use some other naming convention for the class, such as a"C_" or  "Class_" prefix: fhir:C_code or fhir:Class_code

**Comment by dbooth-boston** [comment]
I propose eliminating options 2 and 4, which I think @ericprud suggested on Thursday's call.

**Comment by dbooth-boston** [comment]
Option 3 would have the benefit that all classes would then uniformly start with an upper case letter.  I think I'm favoring option 3, because it gives that uniformity while avoiding punning, even though it slightly doesn't align with the lower case FHIR spelling of the type ("code").

**Comment by dbooth-boston** [comment]
Discussed on today's FHIR RDF call: https://www.w3.org/2023/02/06-hcls-minutes.html#t07

Also discussed on Feb 9, and decided to use punning: https://www.w3.org/2023/02/09-hcls-minutes.html#t03

**Comment by ericprud** [comment]
Assuming this is resolved with R5 ballot.
