### ISSUE TITLE
Significant digits in decimal numbers

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/hcls-fhir-rdf#92]
FHIR requires that significant digits be retained in decimal numbers, to indicate the precision of the number.  For example, "1.000" versus "1.0".  But standard JSON does not distinguish 1.000 from 1.0 (as numbers).  Consequently, FHIR JSON requires a custom JSON parser.

How should the significant digits (precision) be retained and indicated in FHIR RDF?

**Comment by ericprud** [comment]
RDF preserves differences in lexical representations of the same value (c.f. [literal equality](https://www.w3.org/TR/rdf11-concepts/#dfn-literal-term-equality)). [SPARQL](https://www.w3.org/TR/sparql11-query/#QSynLiterals) and [Turtle](https://www.w3.org/TR/turtle/#handle-DECIMAL) also preserve them, so I think our only problem is finding a JSON parser that preserves lexical forms rather than parsing them to IEEE754. I believe json.net does this, but we need something for js and probably java.

related rant: http://community.fhir.org/t/why-did-you-break-the-international-json-standard/1367/11

**Comment by gaurav** [comment]
I think [xsd:decimal](https://docstore.mik.ua/orelly/xml/schema/ch16_01.htm#ch16-77036) is intended for this use case -- although it is matched equivalently without conversion (i.e. `"15"^^xsd:byte` and `"15.0"^^xsd:decimal` as per [*XML Schema Datatypes in RDF and OWL*](https://www.w3.org/TR/swbp-xsch-datatypes/#sec-values-examples)), I think RDF systems are supposed to maintain the correct number of significant digits since it is a transferred as a verbatim string.

An alternative would be something like [xsd:precisionDecimal](https://www.w3.org/TR/xsd-precisionDecimal/), which is based on IEEE754. I am not a computer science, but this seems to be similar to how [BigDecimal](https://stackoverflow.com/a/35436935) works.

In either case, we could store the value in JSON-LD as [value objects](https://www.w3.org/TR/json-ld11/#value-objects), e.g. ```{ "@value": "15.0", "@type": "xsd:decimal" }```.

**Comment by ericprud** [comment]
(switching to `15.00` because `15.0` is the [canonical form](https://www.w3.org/TR/xmlschema-2/#decimal-canonical-representation))

I don't think this changes the RDF representation; we just need to warn folks that they might need to use a non-standard JSON parser when converting FHIR JSON to FHIR RDF (just as they would for converting to FHIR XML, or for that matter, parsing FHIR JSON CDS or anything else that cares about those ghostly significant digits that disappear in IEEE754).

**Comment by gaurav** [comment]
After discussing this at the FHIR RDF weekly phone meeting on Thursday, Oct 7, I think we concluded that:
1. As long as FHIR JSON insists that [decimals are represented as JSON numbers](http://build.fhir.org/json.html#primitive), our ability to translate them into strings via JSON-LD contexts is limited. Changing this is noted to be ["impossible under our procedural rules"](http://community.fhir.org/t/why-did-you-break-the-international-json-standard/1367/5).
2. The JSON standard ["allows implementations to set limits on the range and precision of numbers accepted"](https://datatracker.ietf.org/doc/html/rfc8259#section-6), so the main thing to do is to ensure that users of our JSON-LD contexts use a JSON parser that treats numbers as decimals rather than floats.
3. For any software we write that converts JSON-LD into n-Quads or other RDF representations, we can ensure that the software uses a JSON parser that uses decimals rather than floats, and use `xsd:decimal` or `xsd:precisionDecimal` to ensure that the decimal values are not misinterpreted downstream.

Does that sound right to everybody? If so, I think we can close this issue once we add a warning about point 2 to our documentation somewhere.

**Comment by ericprud** [comment]
Re 1, totally agree.

Re 2, I'd guess that requirements for preserving trailing 0s are rarely, if ever, clinical. We cann concoct a scenario where a CDS system changed its recommendation depending on the result of some precision of some calculation (below), but it's not a routine use of FHIR. Any reason we would have to suggest particular behavior pertains to all users of FHIR JSON and should go into the [JSON precision warning](https://build.fhir.org/json.html#decimal). We can link to it to raise awareness.

Re 3, I expect Graham et al would suggest we use the same datatypes as FHIR/XML.

**CDS scenario - renal monitoring**:
1. An EGFR < 45.0 triggers 2 visits/year
2. Patient 41yo female with serum cystatin C of 1.3mg/L.
3. A reported serum creatinine of 1.50 -> EGRR of 45, so follow-up 1/year
4. A reported serum creatinine of 1.51 -> EGRR of 44, so follow-up 2/year
5. A reported serum creatinine of 1.5 in some *highly conservative* CDS system makes a worst-case assumption of 1.54, triggering 2 follow-ups/year (different behavior than for 1.50).

**Comment by dbooth-boston** [comment]
> Re 3, I expect Graham et al would suggest we use the same datatypes as FHIR/XML.

Can you clarify?  Would that be the same or different from what @gaurav suggested above?

**Comment by ericprud** [comment]
XML is like RDF in that the lexical values are preserved. (XSD has canonical forms, which would alter the number of precision digits, but standard processing doesn't invoke canonicalization, in either XML or RDF.) Given that, and the fact that we'd have to discover or invent new analogs to decimal and doubles to specifically advertise that same behavior, I don't think we can justify deviating from what already works in FHIR/XML.

**Comment by dbooth-boston** [comment]
From [minutes of 10/14/21](https://www.w3.org/2021/10/14-hcls-minutes.html#t02):

```
AGREED: All agreed. Close issue 92 with no change to R4.
```
